# Generated by Django 5.2.5 on 2026-03-19 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=5, verbose_name='Type')),
                ('file', models.ImageField(blank=True, upload_to='gallery/photos/', verbose_name='Fichier')),
                ('video_url', models.URLField(blank=True, verbose_name='URL vidéo (YouTube/Vimeo)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='gallery.album', verbose_name='Album')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
