# Generated by Django 5.2.5 on 2025-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=99, max_length=2, verbose_name='Rang'),
        ),
    ]
