# Generated by Django 5.2.5 on 2025-08-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=99, verbose_name='Rang'),
        ),
    ]
